name: Deploy to jrgochan.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install -r requirements-dev.txt
        pytest

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r src deployment/
        cp -r scripts deployment/
        cp app.py deployment/
        cp requirements.txt deployment/
        cp -r data deployment/ || true
        tar -czf monies-deploy.tar.gz deployment

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan jrgochan.io >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        DEPLOY_PATH: /var/www/html/monies
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        scp monies-deploy.tar.gz $SERVER_USER@jrgochan.io:/tmp/
        ssh $SERVER_USER@jrgochan.io "sudo mkdir -p $DEPLOY_PATH && \
                                      sudo rm -rf $DEPLOY_PATH/* && \
                                      sudo tar -xzf /tmp/monies-deploy.tar.gz -C $DEPLOY_PATH --strip-components=1 && \
                                      sudo chown -R www-data:www-data $DEPLOY_PATH && \
                                      cd $DEPLOY_PATH && \
                                      sudo pip install -r requirements.txt && \
                                      sudo systemctl restart nginx"

    - name: Clean up
      run: |
        ssh $SERVER_USER@jrgochan.io "rm /tmp/monies-deploy.tar.gz"

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "Deployment to jrgochan.io/monies completed successfully"
        else
          echo "Deployment to jrgochan.io/monies failed"
        fi
